### ISSUE TITLE
KDE (plasmashell) - Errors/Crashes (segfault) after Update

### ISSUE THREAD

**Issue by DeimosMH** [Nobara-Project/nobara-images#10]
After update plasmashell will segfault after update.

Removing old settings and themes, than cache and reinstalling as below solves problem (in my case, as depending on installed themes it will need to be deducted from logs).
For users who are not proficient with terminal, viable solution may be to revert to use older version of System (should be an options during boot).

The problem can be easily solved via automation script after updating version of KDE/plasmashell for it to not occur if any user will  update it and/or have themes that will conflict with new version:
-> detection of plasmashell  crash after update
-> backup of current settings and themes folder
-> clear themes and cache
-> reinstall plasma workspace
-> inform user 

I belive moving themes and old options will be better than black screen with crashes in loop when you try to run plasmashell (unusable state of system for user). 

Inxi - information about my system
```
deimos@nobara-pc:~$ inxi -Fxz
System:
  Kernel: 6.10.3-201.fsync.fc40.x86_64 arch: x86_64 bits: 64 compiler: gcc
    v: 2.41-37.fc40
  Desktop: KDE Plasma v: 6.1.3 Distro: Nobara Linux 40 (KDE Plasma)
    base: Fedora 40
Machine:
  Type: Laptop System: LENOVO product: 81T3 v: Legion Y540-17IRH-PG0
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: SDK0J40700 WIN
    serial: <superuser required> UEFI: LENOVO v: BHCN45WW date: 05/24/2022
Battery:
  ID-1: BAT0 charge: 50.9 Wh (96.0%) condition: 53.0/52.5 Wh (101.0%)
    volts: 12.4 min: 11.3 model: LGC L17L3PG1 status: not charging
CPU:
  Info: quad core model: Intel Core i5-9300H bits: 64 type: MT MCP
    arch: Coffee Lake rev: A cache: L1: 256 KiB L2: 1024 KiB L3: 8 MiB
  Speed (MHz): avg: 4001 high: 4002 min/max: 800/4100 cores: 1: 4001 2: 4000
    3: 4002 4: 4000 5: 4000 6: 4001 7: 4002 8: 4002 bogomips: 38400
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] vendor: Lenovo
    driver: nvidia v: 555.58.02 arch: Turing bus-ID: 01:00.0
  Device-2: Lite-On Integrated Camera driver: uvcvideo type: USB
    bus-ID: 1-6:8
  Display: wayland server: X.org v: 1.20.14 with: Xwayland v: 24.1.0
    compositor: kwin_wayland driver: N/A resolution: 2560x1440
  API: EGL v: 1.5 drivers: nvidia,swrast,zink platforms:
    active: gbm,wayland,x11,surfaceless,device inactive: device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 555.58.02
    glx-v: 1.4 direct-render: yes renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
  API: Vulkan v: 1.3.280 drivers: N/A surfaces: xcb,xlib,wayland devices: 2
Audio:
  Device-1: Intel Cannon Lake PCH cAVS vendor: Lenovo driver: snd_hda_intel
    v: kernel bus-ID: 00:1f.3
  Device-2: NVIDIA vendor: Lenovo driver: snd_hda_intel v: kernel
    bus-ID: 01:00.1
  Device-3: Superlux digit E205U driver: hid-generic,snd-usb-audio,usbhid
    type: USB bus-ID: 1-4.2:9
  API: ALSA v: k6.10.3-201.fsync.fc40.x86_64 status: kernel-api
  Server-1: JACK v: 1.9.22 status: off
  Server-2: PipeWire v: 1.2.1 status: active
Network:
  Device-1: Intel Cannon Lake PCH CNVi WiFi driver: iwlwifi v: kernel
    bus-ID: 00:14.3
  IF: wlp0s20f3 state: down mac: <filter>
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    vendor: Lenovo driver: r8169 v: kernel port: 3000 bus-ID: 07:00.0
  IF: enp7s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Intel Bluetooth 9460/9560 Jefferson Peak (JfP) driver: btusb
    v: 0.8 type: USB bus-ID: 1-14:13
  Report: btmgmt ID: hci0 rfk-id: 2 state: up address: <filter> bt-v: 5.1
    lmp-v: 10
Drives:
  Local Storage: total: 2.3 TiB used: 1.46 TiB (63.5%)
  ID-1: /dev/nvme0n1 vendor: Patriot model: VPN110 2048GB size: 1.86 TiB
    temp: 26.9 C
  ID-2: /dev/sda vendor: GOODRAM model: SSDPR-CL100-480-G3 size: 447.13 GiB
Partition:
  ID-1: / size: 607.19 GiB used: 453.98 GiB (74.8%) fs: btrfs
    dev: /dev/nvme0n1p3
  ID-2: /boot size: 973.4 MiB used: 536 MiB (55.1%) fs: ext4
    dev: /dev/nvme0n1p2
  ID-3: /boot/efi size: 96 MiB used: 45.4 MiB (47.3%) fs: vfat
    dev: /dev/sda1
  ID-4: /home size: 607.19 GiB used: 453.98 GiB (74.8%) fs: btrfs
    dev: /dev/nvme0n1p3
Swap:
  ID-1: swap-1 type: zram size: 8 GiB used: 256 KiB (0.0%) dev: /dev/zram0
  ID-2: swap-2 type: partition size: 31.81 GiB used: 0 KiB (0.0%)
    dev: /dev/nvme0n1p4
Sensors:
  System Temperatures: cpu: 56.0 C pch: 52.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Info:
  Memory: total: 16 GiB available: 15.52 GiB used: 5.46 GiB (35.2%)
  Processes: 365 Uptime: 54m Init: systemd target: graphical (5)
  Packages: 27 Compilers: gcc: 14.1.1 Shell: Bash v: 5.2.26 inxi: 3.3.34

```

My commands (my solution deducted from logs)
```
mv ~/.config/kdeglobals ~/.config/kdeglobals.bak
mv ~/.config/plasma-org.kde.plasma.desktop-appletsrc ~/.config/plasma-org.kde.plasma.desktop-appletsrc.bak
mv ~/.config/kdeglobals ~/.config/kdeglobals.bak
mv ~/.config/kwinrc ~/.config/kwinrc.bak
mv ~/.config/plasma-org.kde.plasma.desktop-appletsrc ~/.config/plasma-org.kde.plasma.desktop-appletsrc.bak
mv ~/.config/kdeglobals ~/.config/kdeglobals.bak
mv ~/.config/kwinrc ~/.config/kwinrc.bak

rm -rf ~/.local/share/plasma/plasmoids
rm -rf ~/.cache/plasmashell
rm -rf ~/.cache/kactivitymanagerd

sudo dnf update
sudo dnf upgrade
sudo dnf reinstall plasma-workspace-*
```

Error logs:
```
deimos@nobara-pc:~$ plasmashell
KCrash: Attempting to start /usr/bin/plasmashell
KCrash: Application 'plasmashell' crashing... crashRecursionCounter = 2
Segmentation fault (core dumped)


DEBUG:
Application: plasmashell (plasmashell), signal: Segmentation fault

[New LWP 15760]
[New LWP 15752]
[New LWP 15754]
[New LWP 15755]
[New LWP 15753]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `plasmashell'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f893e8a84a4 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f89214006c0 (LWP 15760))]
Cannot QML trace cores :(
[Current thread is 1 (Thread 0x7f89214006c0 (LWP 15760))]

Thread 5 (Thread 0x7f892ae006c0 (LWP 15753)):
#0  0x00007f893e91c67d in poll () at /lib64/libc.so.6
#1  0x00007f893dcb7c34 in g_main_context_iterate_unlocked.isra () at /lib64/libglib-2.0.so.0
#2  0x00007f893dc57383 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007f893f2850a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#4  0x00007f893efa3b03 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#5  0x00007f893f0b7e4f in QThread::exec() () at /lib64/libQt6Core.so.6
#6  0x00007f894107be41 in QDBusConnectionManager::run() () at /lib64/libQt6DBus.so.6
#7  0x00007f893f15463c in QThreadPrivate::start(void*) () at /lib64/libQt6Core.so.6
#8  0x00007f893e8a6507 in start_thread () at /lib64/libc.so.6
#9  0x00007f893e92a40c in clone3 () at /lib64/libc.so.6

Thread 4 (Thread 0x7f89296006c0 (LWP 15755)):
#0  0x00007f893e91c67d in poll () at /lib64/libc.so.6
#1  0x00007f8940775df5 in QtWaylandClient::EventThread::run() () at /lib64/libQt6WaylandClient.so.6
#2  0x00007f893f15463c in QThreadPrivate::start(void*) () at /lib64/libQt6Core.so.6
#3  0x00007f893e8a6507 in start_thread () at /lib64/libc.so.6
#4  0x00007f893e92a40c in clone3 () at /lib64/libc.so.6

Thread 3 (Thread 0x7f892a0006c0 (LWP 15754)):
#0  0x00007f893e91c67d in poll () at /lib64/libc.so.6
#1  0x00007f8940775df5 in QtWaylandClient::EventThread::run() () at /lib64/libQt6WaylandClient.so.6
#2  0x00007f893f15463c in QThreadPrivate::start(void*) () at /lib64/libQt6Core.so.6
#3  0x00007f893e8a6507 in start_thread () at /lib64/libc.so.6
#4  0x00007f893e92a40c in clone3 () at /lib64/libc.so.6

Thread 2 (Thread 0x7f8938c0f400 (LWP 15752)):
#0  0x00007f893e8a2be9 in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f893e8a5639 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#2  0x00007f893f160efb in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /lib64/libQt6Core.so.6
#3  0x00007f89402eae58 in QQmlThread::internalCallMethodInThread(QQmlThread::Message*) () at /lib64/libQt6Qml.so.6
#4  0x00007f8940441f83 in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () at /lib64/libQt6Qml.so.6
#5  0x00007f8940442788 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /lib64/libQt6Qml.so.6
#6  0x00007f8940320a30 in QQmlComponentPrivate::loadUrl(QUrl const&, QQmlComponent::CompilationMode) () at /lib64/libQt6Qml.so.6
#7  0x00007f8941efa84c in PlasmaQuick::SharedQmlEngine::setSource(QUrl const&) () at /lib64/libPlasmaQuick.so.6
#8  0x00007f8941efba58 in PlasmaQuick::QuickViewSharedEngine::setSource(QUrl const&) () at /lib64/libPlasmaQuick.so.6
#9  0x000055d0744ad0aa in DesktopView::DesktopView (this=0x7f892400dbe0, corona=0x55d0b2f1d3c0, targetScreen=0x55d0b2750420) at /usr/src/debug/plasma-workspace-6.1.3-5.fc40.x86_64/shell/desktopview.cpp:65
#10 ShellCorona::addOutput (this=0x55d0b2f1d3c0, screen=0x55d0b2750420) at /usr/src/debug/plasma-workspace-6.1.3-5.fc40.x86_64/shell/shellcorona.cpp:1397
#11 ShellCorona::addOutput (this=0x55d0b2f1d3c0, screen=0x55d0b2750420) at /usr/src/debug/plasma-workspace-6.1.3-5.fc40.x86_64/shell/shellcorona.cpp:1383
#12 0x000055d0744b120f in ShellCorona::loadDefaultLayout (this=0x55d0b2f1d3c0) at /usr/src/debug/plasma-workspace-6.1.3-5.fc40.x86_64/shell/shellcorona.cpp:1068
#13 0x00007f8941c6ec1d in Plasma::Corona::loadLayout(QString const&) () at /lib64/libPlasma.so.6
#14 0x000055d0744b24a4 in ShellCorona::load (this=0x55d0b2f1d3c0) at /usr/src/debug/plasma-workspace-6.1.3-5.fc40.x86_64/shell/shellcorona.cpp:796
#15 0x00007f893effc872 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt6Core.so.6
#16 0x00007f8941249543 in KActivities::Consumer::serviceStatusChanged(KActivities::Consumer::ServiceStatus) () at /lib64/libPlasmaActivities.so.6
#17 0x00007f893effc872 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt6Core.so.6
#18 0x00007f894125837c in KActivities::ActivitiesCache::setAllActivities(QList<ActivityInfo> const&) () at /lib64/libPlasmaActivities.so.6
#19 0x00007f894125e394 in KActivities::ActivitiesCache::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () at /lib64/libPlasmaActivities.so.6
#20 0x00007f893effcbe0 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt6Core.so.6
#21 0x00007f89410d4031 in QDBusPendingCallWatcher::finished(QDBusPendingCallWatcher*) () at /lib64/libQt6DBus.so.6
#22 0x00007f893efedd4b in QObject::event(QEvent*) () at /lib64/libQt6Core.so.6
#23 0x00007f894158b218 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt6Widgets.so.6
#24 0x00007f893ef96dc8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt6Core.so.6
#25 0x00007f893ef9ab91 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt6Core.so.6
#26 0x00007f893f2858ef in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt6Core.so.6
#27 0x00007f893dc55e8c in g_main_context_dispatch_unlocked.lto_priv () at /lib64/libglib-2.0.so.0
#28 0x00007f893dcb7c98 in g_main_context_iterate_unlocked.isra () at /lib64/libglib-2.0.so.0
#29 0x00007f893dc57383 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#30 0x00007f893f2850a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#31 0x00007f893efa3b03 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#32 0x00007f893ef9f9bc in QCoreApplication::exec() () at /lib64/libQt6Core.so.6
#33 0x000055d074477b3a in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/plasma-workspace-6.1.3-5.fc40.x86_64/shell/main.cpp:188

Thread 1 (Thread 0x7f89214006c0 (LWP 15760)):
[KCrash Handler]
#4  0x00007f89403fe434 in QQmlType::QQmlType(QQmlType const&) () at /lib64/libQt6Qml.so.6
#5  0x00007f894040f9d5 in QQmlPropertyCacheCreator<QQmlTypeCompiler>::propertyCacheForObject(QmlIR::Object const*, QQmlBindingInstantiationContext const&, QQmlError*) const () at /lib64/libQt6Qml.so.6
#6  0x00007f894041f109 in QQmlPropertyCacheCreator<QQmlTypeCompiler>::buildMetaObjectRecursively(int, QQmlBindingInstantiationContext const&, QQmlPropertyCacheCreator<QQmlTypeCompiler>::VMEMetaObjectIsRequired) () at /lib64/libQt6Qml.so.6
#7  0x00007f894041f4c2 in QQmlPropertyCacheCreator<QQmlTypeCompiler>::buildMetaObjectRecursively(int, QQmlBindingInstantiationContext const&, QQmlPropertyCacheCreator<QQmlTypeCompiler>::VMEMetaObjectIsRequired) () at /lib64/libQt6Qml.so.6
#8  0x00007f894041fb98 in QQmlPropertyCacheCreator<QQmlTypeCompiler>::buildMetaObjectsIncrementally() () at /lib64/libQt6Qml.so.6
#9  0x00007f894040e152 in QQmlTypeCompiler::compile() () at /lib64/libQt6Qml.so.6
#10 0x00007f8940421925 in QQmlTypeData::compile(QQmlRefPointer<QQmlTypeNameCache> const&, QV4::ResolvedTypeReferenceMap*, std::function<QByteArray ()> const&) () at /lib64/libQt6Qml.so.6
#11 0x00007f894042999e in QQmlTypeData::done() () at /lib64/libQt6Qml.so.6
#12 0x00007f8940331065 in QQmlDataBlob::tryDone() () at /lib64/libQt6Qml.so.6
#13 0x00007f89404412a0 in QQmlTypeLoader::setData(QQmlRefPointer<QQmlDataBlob> const&, QQmlDataBlob::SourceCodeData const&) () at /lib64/libQt6Qml.so.6
#14 0x00007f8940441bb9 in QQmlTypeLoader::setData(QQmlRefPointer<QQmlDataBlob> const&, QString const&) () at /lib64/libQt6Qml.so.6
#15 0x00007f8940441cc0 in QQmlTypeLoader::loadThread(QQmlRefPointer<QQmlDataBlob> const&) () at /lib64/libQt6Qml.so.6
#16 0x00007f89404420ea in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () at /lib64/libQt6Qml.so.6
#17 0x00007f8940442788 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /lib64/libQt6Qml.so.6
#18 0x00007f8940427edd in QQmlTypeData::resolveTypes() () at /lib64/libQt6Qml.so.6
#19 0x00007f894042c209 in QQmlTypeData::allDependenciesDone() () at /lib64/libQt6Qml.so.6
#20 0x00007f894044141b in QQmlTypeLoader::setData(QQmlRefPointer<QQmlDataBlob> const&, QQmlDataBlob::SourceCodeData const&) () at /lib64/libQt6Qml.so.6
#21 0x00007f8940441bb9 in QQmlTypeLoader::setData(QQmlRefPointer<QQmlDataBlob> const&, QString const&) () at /lib64/libQt6Qml.so.6
#22 0x00007f8940441cc0 in QQmlTypeLoader::loadThread(QQmlRefPointer<QQmlDataBlob> const&) () at /lib64/libQt6Qml.so.6
#23 0x00007f894044f1dc in QQmlThread::createMessageFromMethod<void (QQmlTypeLoaderThread::*)(QQmlRefPointer<QQmlDataBlob> const&), QQmlRefPointer<QQmlDataBlob> const&>(void (QQmlTypeLoaderThread::*&&)(QQmlRefPointer<QQmlDataBlob> const&), QQmlRefPointer<QQmlDataBlob> const&)::I::call(QQmlThread*) () at /lib64/libQt6Qml.so.6
#24 0x00007f89402eab5d in QQmlThreadPrivate::threadEvent() () at /lib64/libQt6Qml.so.6
#25 0x00007f89402eb5fd in QQmlThreadPrivate::event(QEvent*) () at /lib64/libQt6Qml.so.6
#26 0x00007f894158b218 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt6Widgets.so.6
#27 0x00007f893ef96dc8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt6Core.so.6
#28 0x00007f893ef9ab91 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt6Core.so.6
#29 0x00007f893f2858ef in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt6Core.so.6
#30 0x00007f893dc55e8c in g_main_context_dispatch_unlocked.lto_priv () at /lib64/libglib-2.0.so.0
#31 0x00007f893dcb7c98 in g_main_context_iterate_unlocked.isra () at /lib64/libglib-2.0.so.0
#32 0x00007f893dc57383 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#33 0x00007f893f2850a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#34 0x00007f893efa3b03 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt6Core.so.6
#35 0x00007f893f0b7e4f in QThread::exec() () at /lib64/libQt6Core.so.6
#36 0x00007f893f15463c in QThreadPrivate::start(void*) () at /lib64/libQt6Core.so.6
#37 0x00007f893e8a6507 in start_thread () at /lib64/libc.so.6
#38 0x00007f893e92a40c in clone3 () at /lib64/libc.so.6
```

Terminal
```
deimos@nobara-pc:~$ plasmashell 
KPackageStructure of KPluginMetaData(pluginId:"OnlyText.Date.Kde", fileName: "/home/deimos/.local/share/plasma/plasmoids/OnlyText.Date.Kde/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"Redmi.Clock", fileName: "/home/deimos/.local/share/plasma/plasmoids/Redmi.Clock/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"zayron.chaac.weather", fileName: "/home/deimos/.local/share/plasma/plasmoids/zayron.chaac.weather/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"zayron.simple.separator", fileName: "/home/deimos/.local/share/plasma/plasmoids/zayron.simple.separator/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"org.kpple.kppleMenu", fileName: "/home/deimos/.local/share/plasma/plasmoids/org.kpple.kppleMenu/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"Weather.IntiSol.kde", fileName: "/home/deimos/.local/share/plasma/plasmoids/Weather.IntiSol.kde/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"Plasma.Control.Hub", fileName: "/home/deimos/.local/share/plasma/plasmoids/Plasma.Control.Hub/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"org.kde.windowtitle.Fork", fileName: "/home/deimos/.local/share/plasma/plasmoids/org.kde.windowtitle.Fork/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"Date.Urban.kde", fileName: "/home/deimos/.local/share/plasma/plasmoids/Date.Urban.kde/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"org.kde.plasma.win7showdesktop", fileName: "/usr/share/plasma/plasmoids/org.kde.plasma.win7showdesktop/metadata.json") does not match requested format "Plasma/Applet"
KCrash: Attempting to start /usr/bin/plasmashell
KCrash: Application 'plasmashell' crashing... crashRecursionCounter = 2
Segmentation fault (core dumped)
deimos@nobara-pc:~$ KPackageStructure of KPluginMetaData(pluginId:"OnlyText.Date.Kde", fileName: "/home/deimos/.local/share/plasma/plasmoids/OnlyText.Date.Kde/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"Redmi.Clock", fileName: "/home/deimos/.local/share/plasma/plasmoids/Redmi.Clock/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"zayron.chaac.weather", fileName: "/home/deimos/.local/share/plasma/plasmoids/zayron.chaac.weather/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"zayron.simple.separator", fileName: "/home/deimos/.local/share/plasma/plasmoids/zayron.simple.separator/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"org.kpple.kppleMenu", fileName: "/home/deimos/.local/share/plasma/plasmoids/org.kpple.kppleMenu/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"Weather.IntiSol.kde", fileName: "/home/deimos/.local/share/plasma/plasmoids/Weather.IntiSol.kde/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"Plasma.Control.Hub", fileName: "/home/deimos/.local/share/plasma/plasmoids/Plasma.Control.Hub/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"org.kde.windowtitle.Fork", fileName: "/home/deimos/.local/share/plasma/plasmoids/org.kde.windowtitle.Fork/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"Date.Urban.kde", fileName: "/home/deimos/.local/share/plasma/plasmoids/Date.Urban.kde/metadata.json") does not match requested format "Plasma/Applet"
KPackageStructure of KPluginMetaData(pluginId:"org.kde.plasma.win7showdesktop", fileName: "/usr/share/plasma/plasmoids/org.kde.plasma.win7showdesktop/metadata.json") does not match requested format "Plasma/Applet"
KCrash: Attempting to start /usr/bin/plasmashell
KCrash: Application 'plasmashell' crashing... crashRecursionCounter = 2
```

**Comment by DeimosMH** [comment]
I think I have made a mistake - it should be posted in [rpm-sources](https://github.com/Nobara-Project/rpm-sources)
I will close the issue here and post it in ```rpm-sources ```...
Apologies for that.

**Comment by DeimosMH** [comment]
Link to posted issue: [KDE (segfault) after Update](https://github.com/Nobara-Project/rpm-sources/issues/77)
